### ISSUE TITLE
note  sent to icsm16 review  team re COI

### ISSUE THREAD

**Issue by timm** [researchart/all#2]

**Comment by timm** [comment]
Next step:
-  [x] change icsme16 instructions to "accept reject" rather than platinum diamond etc
-  [x] make  icsem16/fse16  review assignments . should not be too hard... most of them have volunteered for the right number of papers

if i do the first one, can  @obaysal   wanna volunteer to do the second?

**Comment by timm** [comment]
> change icsme16 instructions to "accept reject" rather than platinum diamond etc

fyi, i just have:
- changed the list of allowed decisions in the master tracking sheet
- changed the labels in github
- changed the instructions on the master sheet p1, see https://docs.google.com/spreadsheets/d/13sPyQvb7D1Scuof-1ERfqsKn0KNMUy-J2JJRtwsJkrQ/edit#gid=1667634552

Please review and check the last item. Thanks!

**Comment by obaysal** [comment]
@timm sure, I will do paper assignment and get back to you with it. thanks for changing the labels and all updates!

**Comment by obaysal** [comment]
Review assignment is done. See https://docs.google.com/spreadsheets/d/13sPyQvb7D1Scuof-1ERfqsKn0KNMUy-J2JJRtwsJkrQ/edit#gid=935623866. 
-  [x] make  icsem16/fse16  review assignments. 

@timm  I have assigned reviewers' IDs to issues. Some reviewers have not accepted our invite to join reviewers' team on GH. Those IDs are missing from issues. 

Should we ping now reviewers to let them know of their loads and papers?

**Comment by obaysal** [comment]
Papers per reviewers is also updated: https://docs.google.com/spreadsheets/d/13sPyQvb7D1Scuof-1ERfqsKn0KNMUy-J2JJRtwsJkrQ/edit#gid=1872105011.
